@baseurl=http://localhost:3000
@userToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lbGxpc2F3YW5qYTI1NEBnbWFpbC5jb20iLCJzdWIiOiI4MGJjZjlhNS1lNjZkLTRhMzctODc0OC0xNDdjMDg4YTM3MTQiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MDYzNTU4MCwiZXhwIjoxNzUwNjM5MTgwfQ.CWhsJth9wun9pITXdd5xVynDsEenFE5avJ1bSvDy1ZU
@productId= e32882f1-5add-4c65-ad13-2d04cb7de439
@cartItemId= 5d8be8df-edfd-4240-9625-c176cab8f3ad

##e32882f1-5add-4c65-ad13-2d04cb7de439

### Get user cart
GET {{baseurl}}/cart
Authorization: Bearer {{userToken}}

### Add product to cart
POST {{baseurl}}/cart/items
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "productId": "{{productId}}",
  "quantity": 1
}

### Update cart item quantity
PUT {{baseurl}}/cart/items/{{cartItemId}}
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "quantity": 3
}

### Remove item from cart
DELETE {{baseurl}}/cart/items/{{cartItemId}}
Authorization: Bearer {{userToken}}

### Clear cart
DELETE {{baseurl}}/cart
Authorization: Bearer {{userToken}}