@baseurl= http://localhost:3000
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikdlb3JnZUBnbWFpbC5jb20iLCJzdWIiOiJjbWNhazZkZ2owMDAxZzVhOGxlcmFxOG1uIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NTA3NzE5ODksImV4cCI6MTc1MDc3NTU4OX0.Q1bVtNg1fuilF8FRJWr9Abm-gGClB3xAH12OqBamYsE

###Get user profile
GET {{baseurl}}/users/get-profile
Authorization: Bearer {{authToken}}

### Update user profile
PUT {{baseurl}}/users/update-profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Mel Name",
  "email": "mel@example.com"
}


### Delete user account
DELETE {{baseurl}}/users/delete
Authorization: Bearer {{authToken}}